### PR TITLE
Feature: support openQASM serialization of h gate

### PR DESCRIPTION
**Pull request by valegogu**
*Issue #, if available:*
[329](https://github.com/aws/amazon-braket-sdk-python/issues/329)

*Description of changes:*
Added support for openQASM serialization of h gate.

*Testing done:*
Added/ran unit tests with 100% coverage. 
Created/ran test script below as an integration test.
```
circuit = Circuit().h(0)
print(f"{circuit.to_ir(ir_type=IRType.OPENQASM).source}")
d = AwsDevice("arn:aws:braket:::device/quantum-simulator/amazon/sv1")
task = d.run(circuit.to_ir(ir_type=IRType.OPENQASM), shots=10)
res = task.result()
print(res)
```

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [X] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) doc
- [X] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [X] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-sdk-python/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [X] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [X] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ajberdy** [comment]
Looks great! I would recommend editing the description to include a full link to the github issue, which github will render as #329)

**Comment by ajberdy** [comment]
The fix for the failed tests is now in the `feature/openqasm_generation` branch. To get these tests to pass, please go to your fork and press "fetch upstream" and then from your repo locally run `git pull origin feature/openqasm_generation --rebase`. That should fix this

**Comment by ajberdy** [comment]
You're on the right track with bringing in the fix from main-- now you just need to get it into this branch so the tests can pass

**Review by ajberdy — APPROVED** [review]
Nice work!

**Review by wrasmuss — APPROVED** [review]
looks great!

**Pull request merged**
