### PR TITLE
feature: implement serialization of openQASM of I-gate

### PR DESCRIPTION
**Pull request by synthia2080**
*Issue #, if available:*
#329 

*Description of changes:*
Implented openQASM serialization of I-gate.

*Testing done:*
Ran linters and unit-tests as well as practice code to verify result is successful.
'''
circuit = Circuit().i(0)
print(f"{circuit.to_ir(ir_type=IRType.OPENQASM).source}")

d = AwsDevice("arn:aws:braket:::device/quantum-simulator/amazon/sv1")
task = d.run(circuit.to_ir(ir_type=IRType.OPENQASM), shots=10)
print(f"{task.id}")
res = task.result()

print(res)
'''

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [X] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) doc
- [X] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [X] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-sdk-python/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [X] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [X] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ajberdy — APPROVED** [review]
looks great! note: if we're gonna have 2 gates implemented in this commit, make sure to call them both out in the squashed commit message

**Comment by synthia2080** [comment]
> looks great! note: if we're gonna have 2 gates implemented in this commit, make sure to call them both out in the squashed commit message

Thank you! and I apologize about that, I didn't realize this push included the ry gate commits as well.

**Comment by ajberdy** [comment]
Awesome, just the I gate now; looks good!

**Comment by synthia2080** [comment]
> Awesome, just the I gate now; looks good!

Thank you!

**Comment by ajberdy** [comment]
Somehow a blank line ended up in the test file, which is making the lint check complain. If you fix that/run the linters, you should be good!

**Review by ajberdy — APPROVED** [review]

**Pull request merged**
