### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by himanshu007-creator**
*Issue #, if available:* #271

*Description of changes:*

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) doc
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-sdk-python/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by math411** [comment]
Hello and thank you for your pull request. Would you please update the commit message and pull request message to have some information related to the change? Also some of the checks are failing. Locally, you can run `tox` in the package path to see the trace.

**Comment by himanshu007-creator** [comment]
> Hello and thank you for your pull request. Would you please update the commit message and pull request message to have some information related to the change? Also some of the checks are failing. Locally, you can run `tox` in the package path to see the trace.

okay, I will make the required changes.

**Comment by kshitijc** [comment]
Hello @himanshu007-creator! Checking in to see if you are you still planning on updating this PR.

**Comment by himanshu007-creator** [comment]
> Hello @himanshu007-creator! Checking in to see if you are you still planning on updating this PR.

Hi, i am working on this , but could'nt do it. Please help me for these changes. Thanks

**Comment by kshitijc** [comment]
> > Hello @himanshu007-creator! Checking in to see if you are you still planning on updating this PR.
> 
> Hi, i am working on this , but could'nt do it. Please help me for these changes. Thanks

Could you please describe what you're stuck on, so that we can help you here ?

**Comment by kshitijc** [comment]
Closing since there have been no updates on this PR. Please feel free to reopen if you wish to make changes.

**Pull request closed without merging**
