### PR TITLE
fix: LocalQuantumJob.create() fails  on Windows

### PR DESCRIPTION
**Pull request by marcianomoreno**
*Issue #440 *

*Description of changes:*
Updated Path calls to PurePosixPath for the destination directory.
*Testing done:*
Tested the fix as described in the issue in Windows and WSL.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-sdk-python/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
[integ-aws-win-20220916T1742.log](https://github.com/aws/amazon-braket-sdk-python/files/9590481/integ-aws-win-20220916T1742.log)
[integ-aws-wsl-20220916T1758.log](https://github.com/aws/amazon-braket-sdk-python/files/9590485/integ-aws-wsl-20220916T1758.log)

### CODE REVIEW

**Comment by ajberdy** [comment]
I see, these paths are on the image and not the local device, so should be posix even if run on a windows device. Thanks for catching.

**Comment by marcianomoreno** [comment]
I'm glad to be of assistance.

**Comment by ajberdy** [comment]
The build is failing due to linting errors. Could you please update your PR to resolve these? Thank you!

You can run `tox -e linters` for more details on the errors

**Comment by marcianomoreno** [comment]
I will look at the linting errors now and update the PR ASAP.

**Comment by marcianomoreno** [comment]
I have already fixed the linting issue and published the change in this PR.

**Comment by marcianomoreno** [comment]
I generated the documentation locally and noticed some errors which I think are unrelated to the changes I performed. Please refer to the attached log.
[docs-20220917T1303.txt](https://github.com/aws/amazon-braket-sdk-python/files/9592348/docs-20220917T1303.txt)

Let me know if something is needed from my end.

**Review by ajberdy — APPROVED** [review]

**Pull request merged**
