### PR TITLE
feature: added controlled-sqrt-not gate

### PR DESCRIPTION
**Pull request by unprovable**
This makes certain circuits, like CHSH, more straightforward. This commit works in line with the following branches (also committed, separately):
https://github.com/unprovable/amazon-braket-schemas-python.git@ctrl-v-gate
https://github.com/unprovable/amazon-braket-default-simulator-python.git@ctrl-v-gate

*Issue #, if available:*

*Description of changes:*

Added the controlled version of the sqrt(NOT) gate, in Braket's parlance this is the V-gate, and so it is named the 'CV-gate' in this PR. I have also made the relevant changes on similarly named branches in the `schemas` and `default-simulator` repos. These are located:

* https://github.com/unprovable/amazon-braket-schemas-python.git@ctrl-v-gate
* https://github.com/unprovable/amazon-braket-default-simulator-python.git@ctrl-v-gate

(I'll include this PR number in the PRs for those repositories). 

The main motivation for this change is to make circuits a little easier to construct in the simulator, and hopefully later on devices. For example, the CHSH form of the Bell inequality test has a very straightforward form using this gate. (See the 'testing' section for the code that demonstrates this). 
 
*Testing done:*

I wrote some unit tests and included them in the PR. Also, to check this point the following code was used, based on section 16.2 in https://arxiv.org/abs/1907.09415 - 

```
from braket.circuits import circuit, Circuit, Gate, Moments
from braket.circuits.instruction import Instruction
from braket.devices import LocalSimulator
import numpy as np

def chsh_circuit():
    """
    function to perform CHSH form of Bell Inequality Test.
    Based on material in 1907.09415, Section 16.2 (arXiv)
    """

    # instantiate circuit object
    circuit = Circuit()
    
    # put referees in superposition
    circuit.h(2)
    circuit.h(3)
    
    #entangle Alice and Bob
    circuit.h(0)
    circuit.cnot(0, 1)
    
    # spin Alice
    circuit.rx(0, -(3*np.pi)/16)
    
    # apply sqrt(NOT) based on referees flip
    circuit.cv(2,0)
    circuit.cv(3,1)

    return circuit

device = LocalSimulator()
cq = chsh_circuit()
my_task = device.run(cq, shots=1000)
my_task.result()

# check win percentage - should be around 85%, and certainly over 75%.
wins = 0
for i in my_task.result().measurements:
    if i[0] ^ i[1] == i[2] & i[3]:
        wins += 1

print((wins/len(my_task.result().measurements))*100)
```
This circuit produces the correct results using a modified version of the `amazon-braket-sdk` library. The code has been copied into this (and related) PR's to enable these simulations in the main AWS braket repo. 

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-sdk-python/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by unprovable** [comment]
I'm guessing given this was submitted over two weeks ago and no comments have been forthcoming that this probably isn't going anywhere? 

This gate makes a lot of the research I'm currently doing much more workable, hence the code was sent up. Can someone close this (and the other related PR's) if it's not going to be used? Thanks :) M.

**Review by kshitijc — COMMENTED** [review]
Thanks for this PR @unprovable and apologies for missing this earlier. Could you please run `tox -e linters` for fixing the file formatting ?

**Comment by unprovable** [comment]
Hello! No worries - and yes, sorry, forgot to run that. Ran it on all the repos to be sure, but only changes made to the `sdk` repo. Commited and pushed up.

**Review by kshitijc — COMMENTED** [review]
Let's revert tox.ini here as well before we merge. Thanks!

**Review by kshitijc — APPROVED** [review]
Thank you for contributing to enhance the Braket SDK and being patient as we worked through the PRs, @unprovable! Great work!

**Comment by unprovable** [comment]
Thank you for all your help! :D Very nice experience doing these PR's for sure!

**Pull request merged**
